version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  relative-path-mode: gomod

linters:
  default: standard

  enable:
    - bodyclose
    - errorlint
    - gosec
    - misspell
    - nolintlint
    - sqlclosecheck

  exclusions:
    generated: strict

    presets:
      - common-false-positives
      - std-error-handling

    rules:
      - path: _test\.go
        linters:
          - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
