server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: "3306"
  user: root
  database: go_user_system
jwt:
  expireHours: 24
http:
  server:
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    readHeaderTimeout: 2s
    MaxHeaderBytesKib: 512
