server:
  port: 8082
mysql:
  host: 127.0.0.1
  port: "3306"
  user: root
  database: go_user_system
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifeTime: 30m
  connMaxIdleTime: 5m
  pingTimeout: 3s
jwt:
  expireHours: 24
http:
  server:
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    readHeaderTimeout: 2s
    maxHeaderBytesKib: 128
    timeout: 5m
