apiVersion: v1
kind: Service
metadata:
  name: go-user-system-frontend
  namespace: go-user-system
spec:
  selector:
    app: go-user-system-frontend
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP
