apiVersion: v1
kind: Secret
metadata:
  name: go-user-system-secret
  namespace: go-user-system
type: Opaque
stringData:
  DB_PASSWORD: "root.0303AndAdmin"
  JWT_SECRET: "replace_with_a_32_plus_chars_random_secret"
