apiVersion: v1
kind: Secret
metadata:
  name: go-user-system-secret
  namespace: go-user-system
type: Opaque
stringData:
  DB_ROOT_PASSWORD: "replace_with_a_separate_root_password"
  DB_PASSWORD: "replace_with_a_strong_database_password"
  JWT_SECRET: "replace_with_a_32_plus_chars_random_secret"
